#!/bin/bash
#Prints the amount of free memory on the system and saves it
free -h > ~/backups/freemem/free_mem.txt
#Prints disk usage and saves it
file du -h > ~/backups/diskuse/disk_usage.txt
#Lists all open files and saves it
file Isof > ~/backups/openlist/open_list.txt
#Prints file system disk space statistics and saves it
file df -h > ~/backups/freedisk/free_disk.txt
